Repository libusb/hidapi, pull requests merged in 2019-06, with the labels that each got.

#3 mac: fix behaviour of hid_get_feature_report (was writing on the repo…
  mac/hid.c
Labels: bug

#19 README: Add table of contents & fix markdown
  README.md
Labels: documentation

#21 Fix doc string for hid_enumerate
  hidapi/hidapi.h
Labels: bug, documentation
