Repository libusb/hidapi, pull requests merged in 2022-04, with the labels that each got.

#397 darwin: add option to open device in non-exclusive mode
  mac/hid.c
  mac/hidapi_darwin.h
Labels: macOS

#398 Fire v0.12.0
  VERSION
  hidapi/hidapi.h
  hidtest/Makefile.am
  hidtest/test.c
  libusb/hidapi_libusb.h
  mac/Makefile-manual
  mac/hidapi_darwin.h
  windows/hidapi_winapi.h
Labels: Release

#395 libusb: Fix double free of buffer pointer in hid_close()
  libusb/hid.c
Labels: libusb
