Repository libusb/hidapi, pull requests merged in 2023-08, with the labels that each got.

#606 Refine CTest args
  .github/workflows/builds.yml
Labels: build system/CI

#601 hidraw: report only Top-Level Usage_page/Usage pairs as 'unique' devices
  libusb/hid.c
  linux/hid.c
Labels: hidraw

#611 macOS: Check for macOS 10.10 using kCFCoreFoundationVersionNumber instead of AppKit
  configure.ac
  dist/hidapi.podspec
  mac/CMakeLists.txt
  mac/Makefile-manual
  mac/hid.c
Labels: macOS
