Repository libusb/hidapi, pull requests merged in 2023-11, with the labels that each got.

#637 Don't try to memcpy() to a NULL destination.
  mac/hid.c
Labels: bug, macOS

#639 CMake: Do not install pkgconfig
  src/CMakeLists.txt
Labels: CMake

#640 Doc: Fix target documentation
  BUILD.cmake.md
Labels: documentation

#641 Fix the windows build by fixing printf related issues
  .github/workflows/builds.yml
  hidtest/test.c
  libusb/hid.c
  windows/hidapi_descriptor_reconstruct.h
  windows/pp_data_dump/pp_data_dump.c
  windows/test/hid_report_reconstructor_test.c
Labels: build system/CI, Windows, libusb

#644 pthread_barrier_wait: properly check the wait condition
  mac/hid.c
Labels: bug, macOS
